# Original idea and credit go to https://github.com/vroland/epdiy-hardware/blob/main/.github/workflows/main.yml
# Modded for M0WUT library

name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: install kicad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install kicad
      - run: kicad-cli version
      - name: install kikit
        run: |
          pip install kikit
          pip install mistune==2.0.5 
          pip install PcbDraw
          sudo apt install make cmark xsltproc librsvg2-bin
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout M0WUT libraries
        uses: actions/checkout@v4
        with:
          repository: git@github.com:M0WUT/kicad_libraries.git
          token: ${{ secrets.ACTIONS_KEY}}