name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  kicad-cli:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:nightly-202404
    steps:
      - name: Kicad cli tasks
        run: |
          ls
          HOME=/home/kicad/
          cd
          git clone ${{ github.server_url }}/${{ github.repository }} checkout
          git clone https://github.com/M0WUT/kicad_libraries.git wut-libraries
          git clone https://github.com/openscopeproject/InteractiveHtmlBom.git ibom
          git clone https://github.com/M0WUT/kicad_releaser.git kicad_releaser
          kicad-cli version
          sudo apt update
          sudo apt install -y protobuf-compiler
          pwd
          cd checkout
          pwd
          ls
          kicad-cli pcb render --background opaque -o ../output/front_render.png "`ls | grep ".kicad_pcb"`"
          kicad-cli pcb render --rotate 0,180,0 --background opaque -o ../output/back_render.png "`ls | grep ".kicad_pcb"`"

  kikit-cli:
    runs-on: ubuntu-latest
    container:
      image: yaqwsx/kikit
    steps:
        - run: kikit --help




  artefacts:
    runs-on: ubuntu-latest
    needs: 
      - kicad-cli
      - kikit-cli
    steps:
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: /github/home/build/
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: artefacts
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 
      - name: Webpage URL
        run: echo ${{ steps.deployment.outputs.page_url }}

    
      
      

      
          
