# Original Idea from https://github.com/vroland/epdiy-hardware/blob/main/.github/workflows/main.yml
# Entirely re-written by M0WUT

name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kicad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install kicad
      - run: kicad-cli version
      - name: install kikit
        run: |
          pip install kikit
          pip install PcbDraw
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout Interactive HTML BoM
        uses: actions/checkout@v4
        with:
          repository: "git@github.com:openscopeproject/InteractiveHtmlBom.git"
