name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  kicad-cli:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:nightly-202404
      options: --user root
    steps:
      - name: Kicad cli tasks
        run: |
          HOME=/home/kicad/
          cd
          git clone ${{ github.server_url }}/${{ github.repository }} checkout
          git clone https://github.com/M0WUT/kicad_libraries.git wut-libraries
          git clone https://github.com/openscopeproject/InteractiveHtmlBom.git ibom
          git clone https://github.com/M0WUT/kicad_releaser.git kicad_releaser
          kicad-cli version
          sudo apt update
          sudo apt install -y protobuf-compiler
          mkdir kicad_cli_output
          mkdir -p ~/.config/kicad/8.0
          cp -r kicad_releaser/kicad_settings/* ~/.config/kicad/8.0
          sed -i "s#PATH_TO_WUT_LIBRARIES#$(readlink -f wut-libraries)#" ~/.config/kicad/8.0/kicad_common.json
          cat ~/.config/kicad/8.0/kicad_common.json
          cd checkout
          kicad-cli pcb render --background opaque -o ../kicad_cli_output/front_render.png "`ls | grep ".kicad_pcb"`"
          kicad-cli pcb render --rotate 0,180,0 --background opaque -o ../kicad_cli_output/back_render.png "`ls | grep ".kicad_pcb"`"

      - uses: actions/upload-artifact@v4
        with:
          name: kicad_cli
          path: /home/kicad/kicad_cli_output/

  kikit-cli:
    runs-on: ubuntu-latest
    container:
      image: yaqwsx/kikit
    steps:
        - run: kikit --help




  artefacts:
    runs-on: ubuntu-latest
    needs: 
      - kicad-cli
      - kikit-cli
    steps:
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: /github/home/build/
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: artefacts
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 
      - name: Webpage URL
        run: echo ${{ steps.deployment.outputs.page_url }}

    
      
      

      
          
