name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kicad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
          sudo apt update
          sudo apt install kicad
          sudo apt install tree
      - name: Install Kikit
        run: |
          pip install kikit
          pip install mistune==2.0.5 
          pip install PcbDraw
          sudo apt install make cmark xsltproc librsvg2-bin
      - run: kicad-cli version
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout Interactive HTML BoM
        uses: actions/checkout@v4
        with:
          repository: "openscopeproject/InteractiveHtmlBom"
          path: ibom
      - name: Checkout M0WUT Kicad Releaser
        uses: actions/checkout@v4
        with:
          repository: "M0WUT/kicad_releaser"
          path: kicad_releaser
      - run: python kicad_releaser/releaser.py . build
      - run: tree
      
      

      
          
