name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  kicad-cli:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:nightly-202404
    steps:
      - name: Install 3rd party programs
        run: |
          sudo apt update

      - name: Change to home directory
        run: |
          cd
          PATH=$PATH:/github/home/.local/bin/
          sudo chmod 777 /github/home
          kicad-cli version
          git clone ${{ github.server_url }}/${{ github.repository }} main
          git clone https://github.com/M0WUT/kicad_libraries.git wut-libraries
          git clone https://github.com/openscopeproject/InteractiveHtmlBom.git ibom
          git clone https://github.com/M0WUT/kicad_releaser.git kicad_releaser
          sudo apt update
          sudo apt install python3-pip protobuf-compiler xvfb -y
          pip install --break-system-packages -r kicad_releaser/requirements.txt
          mkdir -p ~/.config/kicad/8.0
          cp -r kicad_releaser/kicad_settings/* ~/.config/kicad/8.0
          sed -i "s#PATH_TO_WUT_LIBRARIES#$(readlink -f wut-libraries)#" ~/.config/kicad/8.0/kicad_common.json
          cat ~/.config/kicad/8.0/kicad_common.json
          mkdir build
          cd main
          sudo Xvfb :1 -screen 0 640x480x24 &
          DISPLAY=:1 python3 ../kicad_releaser/releaser.py . ../build
          
          
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: /github/home/build/
  kikit-cli:
    runs-on: ubuntu-latest
    container:
      image: yaqwsx/kikit
      volumes:
        - /github/home/main:/kikit
        - /github/home/build:/build
    needs: kicad-cli
    steps:
      - name: test
        run: ls

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: /github/home/build/


  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs:
      - kicad-cli
      - kikit-cli

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 
      - name: Webpage URL
        run: echo ${{ steps.deployment.outputs.page_url }}

    
      
      

      
          
