name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  kicad-cli:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:nightly-202404
      options: --user root
      volumes:
        - /github/home:/home/kicad/kicad_cli_output
    steps:
      - name: Kicad cli tasks
        run: |
          HOME=/home/kicad/
          cd
          git clone ${{ github.server_url }}/${{ github.repository }} checkout
          git clone https://github.com/M0WUT/kicad_libraries.git wut-libraries
          git clone https://github.com/openscopeproject/InteractiveHtmlBom.git ibom
          git clone https://github.com/M0WUT/kicad_releaser.git kicad_releaser
          kicad-cli version
          sudo apt update
          sudo apt install -y protobuf-compiler
          rm -r .config/kicad/8.99/*
          cp -r kicad_releaser/kicad_settings/* .config/kicad/8.99
          sed -i "s#PATH_TO_WUT_LIBRARIES#$(readlink -f wut-libraries)#" ~/.config/kicad/8.99/kicad_common.json
          cd checkout
          kicad-cli pcb render --side top --background opaque -o ../kicad_cli_output/front_render.png "`ls | grep ".kicad_pcb"`"
          kicad-cli pcb render --side bottom --background opaque -o ../kicad_cli_output/back_render.png "`ls | grep ".kicad_pcb"`"

  kikit-cli:
    runs-on: ubuntu-latest
    needs: kicad-cli
    container:
      image: yaqwsx/kikit
      volumes:
        - /github/home:/wut
    steps:
      - run: kikit --help





  artefacts:
    runs-on: ubuntu-latest
    needs: 
      - kicad-cli
      - kikit-cli
    steps:
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: /github/home/build/
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: artefacts
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 
      - name: Webpage URL
        run: echo ${{ steps.deployment.outputs.page_url }}

    
      
      

      
          
