name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4
        with:
          path: checkout

      - name: Checkout M0WUT Libraries
        uses: actions/checkout@v4
        with:
          repository: "M0WUT/kicad_libraries"
          path: wut-libraries

      - name: Checkout Interactive HTML BoM
        uses: actions/checkout@v4
        with:
          repository: "openscopeproject/InteractiveHtmlBom"
          path: ibom

      - name: Checkout M0WUT Kicad Releaser
        uses: actions/checkout@v4
        with:
          repository: "M0WUT/kicad_releaser"
          path: kicad_releaser

      - run: mkdir output

  kicad-cli:
    runs-on: ubuntu-latest
    needs: checkout
    container:
      image: kicad/kicad:nightly-202404
      volumes: 
        - checkout:/home/kicad/checkout
        - output:/home/kicad/output
    steps:
      - name: kicad-cli
        run: |
          HOME=/home/kicad/
          cd
          kicad-cli version
          ls

  kikit-cli:
    runs-on: ubuntu-latest
    needs: checkout
    container:
      image: yaqwsx/kikit
      volumes:
        - ~/checkout:/kikit
        - ~/shared:/output




  artefacts:
    runs-on: ubuntu-latest
    needs: 
      - kicad-cli
      - kikit-cli
    steps:
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: /github/home/build/
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: kicad-cli
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 
      - name: Webpage URL
        run: echo ${{ steps.deployment.outputs.page_url }}

    
      
      

      
          
