# Original Idea from https://github.com/vroland/epdiy-hardware/blob/main/.github/workflows/main.yml
# Entirely re-written by M0WUT

name: Kicad deployment
on:
  push:
    branches: [ main ]
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      # - name: Install Kicad
      #   run: |
      #     sudo add-apt-repository --yes ppa:kicad/kicad-7.0-releases
      #     sudo apt update
      #     sudo apt install kicad
      # - run: kicad-cli version
      # - name: install kikit
      #   run: |
      #     pip install kikit
      #     pip install PcbDraw
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout Interactive HTML BoM
        uses: actions/checkout@v4
        with:
          repository: "openscopeproject/InteractiveHtmlBom"
          path: ibom
      - name: Checkout M0WUT Kicad Releaser
        uses: actions/checkout@v4
        with:
          repository: "M0WUT/kicad_releaser"
          path: kicad_releaser
      - run: cd main
      - run: mkdir build
      - run: pwd
      - run: ls
      - run: python ../kicad_releaser/releaser.py ../build
      

      
          
